// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMEZ7OtE4dlM-oqiuBFls9rUxq7sIYSks',
    appId: '1:248503046269:web:c0f1a7ed5800a0b6952114',
    messagingSenderId: '248503046269',
    projectId: 'pr-v3-e91eb',
    authDomain: 'pr-v3-e91eb.firebaseapp.com',
    storageBucket: 'pr-v3-e91eb.appspot.com',
    measurementId: 'G-3LTGR66VKZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRNwsAZYi_kK_Npf4iYYFCVmTnwPUMNRo',
    appId: '1:248503046269:ios:74d60166da8baea1952114',
    messagingSenderId: '248503046269',
    projectId: 'pr-v3-e91eb',
    storageBucket: 'pr-v3-e91eb.appspot.com',
    iosClientId: '248503046269-3l3puc1d2bqvontpf3g35ps9atfu21vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment1',
  );
}
