// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaSz-K4ALKa7oDasShCwaglXQDw_NAxcM',
    appId: '1:1028110280907:web:b9730115f0a977eb73534e',
    messagingSenderId: '1028110280907',
    projectId: 'pr-v4-33a89',
    authDomain: 'pr-v4-33a89.firebaseapp.com',
    storageBucket: 'pr-v4-33a89.appspot.com',
    measurementId: 'G-J74PCZZGMH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD349nGHmPGGKsHrVsJWsO-ZqBCUSDImdI',
    appId: '1:1028110280907:ios:de409c8f2c4f232273534e',
    messagingSenderId: '1028110280907',
    projectId: 'pr-v4-33a89',
    storageBucket: 'pr-v4-33a89.appspot.com',
    iosBundleId: 'com.example.assignment',
  );
}
